<#
.SYNOPSIS
    以「静默（不弹窗口）+ 脱离当前进程树」的方式启动一个后台进程。

.DESCRIPTION
    为什么不能直接用 Start-Process：
      · Start-Process 起的进程属于当前 PowerShell 的进程树，命令行一结束就可能被一起回收；
      · 所以 mysqld / 后端一直是走 WMI 的 Win32_Process.Create 来脱离进程树的，
        但 WMI 默认会给控制台程序分配一个**新的可见控制台窗口** ——
        App 自动拉起服务时闪出来的那个黑框就是它。

    这个文件把两件事一起解决：给 WMI 传一个 Win32_ProcessStartup：
      ShowWindow = 0（SW_HIDE）
    窗口在进程创建时就是隐藏的（不是"先显示再隐藏"），所以不会闪；
    而且 cmd → .bat → java.exe 这种孙进程会**继承**这个隐藏控制台，
    因此它们也不会各自再弹一个窗口。

    三条路按可用性依次尝试，都能保证「进程脱离本进程树」：
      1. [wmiclass]（System.Management）+ Win32_ProcessStartup —— 首选，最直接；
      2. wscript.exe + 一个 .vbs（命令行落成 UTF-16 文件，再交给 cmd.exe /c 执行）——
         万一机器上没有 System.Management 时的兜底，同样是 SW_HIDE；
      3. 裸 WMI（老写法）—— 极端情况下的最后兜底：会弹一个控制台窗口，
         但至少服务能起来（会打印一条警告）。

.EXAMPLE
    . "$PSScriptRoot\silent-process.ps1"
    Start-SilentProcess -CommandLine "`"$Mysqld`" --defaults-file=`"$IniFile`"" -Tag 'mysqld'
#>

function Test-SystemManagementAvailable {
    <#  PS7 的精简环境里可能没有 System.Management（[wmiclass] 就是它的加速器）  #>
    return ($null -ne ('System.Management.ManagementClass' -as [type]))
}

function New-HiddenStartupInfo {
    <#  Win32_ProcessStartup 实例：ShowWindow = 0 即 SW_HIDE  #>
    $si = ([wmiclass]'Win32_ProcessStartup').CreateInstance()
    $si.ShowWindow = [uint16]0
    return $si
}

function Start-SilentProcess {
    <#
      启动一个「无窗口 + 脱离进程树」的进程。
      返回实际生效的方式：'wmi-hidden' / 'wmi-vbs' / 'wmi-plain'；失败直接抛异常。

      注意：CreateFlags 里的 CREATE_NO_WINDOW(0x08000000) 被 WMI 提供程序拒绝
      （ReturnValue=21 Invalid parameter），所以这里只用 ShowWindow。
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][string]$CommandLine,
        [string]$WorkingDirectory,
        [string]$HelperDir,
        [string]$Tag = 'process'
    )

    if (-not $HelperDir) {
        $HelperDir = Join-Path (Split-Path -Parent $PSScriptRoot) '.run'
    }
    New-Item -ItemType Directory -Force -Path $HelperDir | Out-Null

    # 注意：[string] 类型的参数没传时是**空串**而不是 $null，
    # 而 WMI 的 Create 对 CurrentDirectory='' 会直接返回 21（Invalid parameter），
    # 所以空串必须换成 $null（= 用默认工作目录）。
    $curDir = if ([string]::IsNullOrWhiteSpace($WorkingDirectory)) { $null } else { $WorkingDirectory }

    # ---- 1) WMI + Win32_ProcessStartup（ShowWindow = SW_HIDE）----
    if (Test-SystemManagementAvailable) {
        try {
            $si = New-HiddenStartupInfo
            $cls = [wmiclass]'Win32_Process'
            $rc = $cls.InvokeMethod('Create', @($CommandLine, $curDir, $si))
            if ($rc -eq 0) { return 'wmi-hidden' }
            Write-Host "  静默启动失败（WMI ReturnValue=$rc），改用备用方式…" -ForegroundColor Yellow
        } catch {
            Write-Host "  静默启动失败（$($_.Exception.Message)），改用备用方式…" -ForegroundColor Yellow
        }
    }

    # ---- 2) WMI 起 wscript，由它用 SW_HIDE 把命令交给 cmd 执行 ----
    #  两个实测出来的坑：
    #   · wscript 的 Run 直接执行「"带引号的完整路径" + 参数」时，
    #     有些程序（实测 mysqld.exe）会被它悄悄丢掉，交给 cmd 解析才稳；
    #   · 命令行里有引号 / 中文路径时，作为 wscript 参数传容易被拆坏，
    #     所以写进一个 UTF-16 的命令行文件，VBS 读出来再用（编码/引号都不用操心）。
    try {
        $cmdFile = Join-Path $HelperDir "silent-$Tag.cmdline.txt"
        $vbsFile = Join-Path $HelperDir 'silent-run.vbs'
        Set-Content -Path $cmdFile -Value $CommandLine -Encoding Unicode
        Set-Content -Path $vbsFile -Encoding ascii -Value @(
            "' generated by scripts\silent-process.ps1 -- run a command line with a hidden window",
            'Set fso = CreateObject("Scripting.FileSystemObject")',
            'cmd = Trim(fso.OpenTextFile(WScript.Arguments(0), 1, False, -1).ReadAll())',
            'If Len(cmd) > 0 Then CreateObject("WScript.Shell").Run "cmd.exe /c """ & cmd & """", 0, False'
        )
        $wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'
        $r = Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{
            CommandLine = "`"$wscript`" //B //Nologo `"$vbsFile`" `"$cmdFile`""
        }
        if ($r.ReturnValue -eq 0) { return 'wmi-vbs' }
        Write-Host "  wscript 兜底也失败了（ReturnValue=$($r.ReturnValue)）…" -ForegroundColor Yellow
    } catch {
        Write-Host "  wscript 兜底也失败了（$($_.Exception.Message)）…" -ForegroundColor Yellow
    }

    # ---- 3) 最后兜底：裸 WMI（会弹窗口，但服务能起来）----
    Write-Host '  警告: 只能以普通方式启动，可能会出现一个控制台窗口。' -ForegroundColor Yellow
    $r = Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{ CommandLine = $CommandLine }
    if ($r.ReturnValue -ne 0) { throw "创建进程失败 (ReturnValue=$($r.ReturnValue))" }
    return 'wmi-plain'
}
